[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-sdk = { workspace = true }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "7ca364f3357056ef84dea757b385728bbacd1fe8" }

bincode = "1.3.3"
