[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-sdk = { workspace = true }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "3647076" }
bincode = "1.3.3"
