[package]
version = "0.1.0"
name = "prover"
edition = "2021"

[dependencies]
sp1-sdk = "4.1.0"
rand = "0.8"
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak",  features = ["keccak"], tag = "patch-2.0.2-sp1-4.0.0" }

[build-dependencies]
sp1-build = "4.1.0"
